"""two factor

Revision ID: b0b5f3af03f9
Revises: a3b75e498271
Create Date: 2026-10-01 09:50:43.548237
"""
from alembic import op
import sqlalchemy as sa


revision = 'b0b5f3af03f9'
down_revision = 'a3b75e498271'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###