global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: fastapi
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: containers
    static_configs:
      - targets: ["cadvisor:8080"]