apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-admins
    receivers:
      - uid: email-admins
        type: email
        settings:
          addresses: $ALERT_EMAIL
          singleEmail: true